spring.application.name=mylibrary

spring.datasource.url=jdbc:postgresql://localhost:5433/library
spring.datasource.username=user
spring.datasource.password=password

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=65589fa1e599bef2e75c1470e546141bd2b0b45d82b9f54ff34e00a32ef0aa62
setup.admin.password=SuperSecret123!
